union_pay:
  base:
    path: http://localhost:8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cooperation
    username: cooperation
    password: cooperation
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate